"""Add tzutcinfo to user

Revision ID: a5ff58b95fec
Revises: 0929ac05522b
Create Date: 2023-11-06 10:40:52.432197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5ff58b95fec'
down_revision = '0929ac05522b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tzutcdelta', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('tzutcdelta')

    # ### end Alembic commands ###
