"""Initial database

Revision ID: ea61c2b970c2
Revises:
Create Date: 2023-09-16 21:33:45.783353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea61c2b970c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(
                        length=80), nullable=False),
                    sa.Column('password_hash', sa.String(
                        length=128), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('username')
                    )
    op.create_table('deck',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('shared', sa.Boolean(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('author_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['author_id'], ['user.id'], name='fk_deck_author_id'),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['user.id'], name='fk_deck_user_id'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('card',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('front', sa.String(length=100), nullable=False),
                    sa.Column('back', sa.String(length=100), nullable=False),
                    sa.Column('deck_id', sa.Integer(), nullable=False),
                    sa.Column('revision_due', sa.Date(), nullable=True),
                    sa.Column('knowledge_level', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['deck_id'], ['deck.id'], name='fk_card_deck_id'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card')
    op.drop_table('deck')
    op.drop_table('user')
    # ### end Alembic commands ###
