"""Add shared column to deck

Revision ID: 05773b7b4977
Revises: f3d08aa20b86
Create Date: 2023-09-16 09:23:43.653093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05773b7b4977'
down_revision = 'f3d08aa20b86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deck', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shared', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deck', schema=None) as batch_op:
        batch_op.drop_column('shared')

    # ### end Alembic commands ###
