"""Add Deck owner

Revision ID: f3d08aa20b86
Revises: ea67832a49a5
Create Date: 2023-09-13 09:52:10.968072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3d08aa20b86'
down_revision = 'ea67832a49a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deck', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_deck_owner_id', 'user', ['owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deck', schema=None) as batch_op:
        batch_op.drop_constraint('fk_deck_owner_id', type_='foreignkey')
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###
